---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: ukodus
spec:
  encryptedData:
    token: AgAbu7kB/RvPn6qd8OCUV7w5umu7p/+3gQQT9nZ1l90sdTWW6HP69rPSl86SzUwhyi/dZX5rC95rXamCf0BVy/iEKvVNNGfHDS0mFvSp+WgBoFMXeY8XFfyUURwICtPR0YoJw0G2AIWAn308II+LMT6HwnqHgQHxo45PQLaOnQBKoy+mFnPsx1GFFohXDPe7vTYsNkKnKkVH/FWxYu75iORmBKjzcNYl8UuPudPdk/vwxnpKSoi1wU+HRL2sqiOBzdd9ibbs+xBLihWQASbP4H34M7ed5CGPDdAgjYfoLLRUL12jUVpr+EfI682VwnL/2AXNPIdJYnKlPu8TlRjBnlsd1DIJkmqp6QlzDr3g9tAgx6p/2iTLQkx3IfPhBfrRNqoqtp8P6qkRhxmAlXmTtg3a4yIdT5Bk3ZfEu7Iu5hyrX1KJZ9A/77NysuqrkGiZj3GlQw/SrMbFT4Uw+LBUqdsUD7KTDoSR3yuBegfUIIAoa+Pz54HSl3VM3nQAE5lQ6zsu9F6zZDc63YUUqNy95qa12xxWaVYrjG+tYLp+ioSHwUBCjL5pm6cz2w5BWDgHHFvNe5v4rai9+xc+EHy7s/A6K9vMDMchYiQLOAEabcrcazvMxdjug5gjDTcBZ+r22mEqMRIcWEcUdX3xhSh14RgBsFnpfqQIckBADhY88rpPurfmypUw4+m/CCJ+UJ52oAJPGCnenA+f4XcP42CpO+xFPbx5rEBXISeLQnc9UYtdbtj/6QFtE/3y/Pz5fWHcZ0kLo7TweqaHZybxPG5V4ewoKq5u8k8e4iSkflJOhQYYYlootFlze+9QukxmIYO/u+xtJl99Rob2gPnyS7IGZ5ryaiCqvTBxHSue7tYNqush7a9DW46aTVPw2OfK/gs0AUisSWhuQucvXUKoMjCShCPw1tFcZWA7cKwajaq4ENug9tC8cYw=
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: ukodus
