apiVersion: v1
kind: Service
metadata:
  name: ukodus-api
  namespace: ukodus
  labels:
    app: ukodus-api
spec:
  type: ClusterIP
  selector:
    app: ukodus-api
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
