apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: ukodus
  labels:
    app: ukodus-api
spec:
  selector:
    app: ukodus-api
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
