apiVersion: apps/v1
kind: Deployment
metadata:
  name: ukodus-frontend
  namespace: ukodus
  labels:
    app: ukodus-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ukodus-frontend
  template:
    metadata:
      labels:
        app: ukodus-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: frontend
          image: ghcr.io/kcirtapfromspace/ukodus-frontend:latest
          envFrom:
            - secretRef:
                name: posthog-config
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
