apiVersion: apps/v1
kind: Deployment
metadata:
  name: ukodus-frontend
  namespace: ukodus
  labels:
    app: ukodus-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ukodus-frontend
  template:
    metadata:
      labels:
        app: ukodus-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/kcirtapfromspace/ukodus-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
