apiVersion: v1
kind: Service
metadata:
  name: ukodus-frontend
  namespace: ukodus
  labels:
    app: ukodus-frontend
spec:
  type: ClusterIP
  selector:
    app: ukodus-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
