apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ukodus-ingress
  namespace: ukodus
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/upstream-hash-by: "$remote_addr"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location ~* /api/v1/ws/ {
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_http_version 1.1;
      }
spec:
  ingressClassName: nginx
  rules:
    - host: ukodus.now
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ukodus-api
                port:
                  number: 3000
          - path: /s
            pathType: Prefix
            backend:
              service:
                name: ukodus-api
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ukodus-frontend
                port:
                  number: 80
