apiVersion: v1
kind: Secret
metadata:
  name: ukodus-secrets
  namespace: ukodus
type: Opaque
data:
  neo4j-password: cGFzc3dvcmQ=    # "password" base64
  neo4j-auth: bmVvNGovcGFzc3dvcmQ=  # "neo4j/password" base64
